### ISSUE TITLE
Number of classes in GeoPlaces Dataset

### ISSUE THREAD

**Issue by ngoctuan1** [ViLab-UCSD/GeoNet#1]
Hi u, I downloaded GeoPlaces Dataset to test. But I found this dataset has a different number of classes than the number of classes you report on paper (205 classes). Specifically, Asia_train and Usa_train have 204 classes, Asia_test has 203 classes and Usa_test has 201 classes.
Thank you.

**Comment by tarun005** [comment]
Some classes have no images in some splits, so the computed accuracy is reported on the categories which are actually present. Specifically,

1. Usa_train doesn't have images from "_kasbah" (id:106)_.
2. Usa_test doesn't have images from "_kasbah (106), yard (204), dinette home(66), temple east asia (183)_".
3. Asia_train doesn't have images from "_kasbah" (106)_.
4. Asia_test doesn't have images from  "_kasbah (106), yard (204)_".

So technically the maximum number of classes we have is 204, but we work with 205 to be compatible with class ids from  Places205.

**Comment by ngoctuan1** [comment]
I understood, thank you for quick reply.
